<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" total="3" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="119291" started-at="2015-05-07T09:55:53Z" finished-at="2015-05-07T09:57:52Z">
    <groups>
      <group name="Login">
        <method signature="LoginTest.loginTest()[pri:0, instance:com.projectname.test.functional.login.LoginTest@1ce487b]" name="loginTest" class="com.projectname.test.functional.login.LoginTest"/>
      </group> <!-- Login -->
      <group name="Regression">
        <method signature="LoginTest.loginTest()[pri:0, instance:com.projectname.test.functional.login.LoginTest@1ce487b]" name="loginTest" class="com.projectname.test.functional.login.LoginTest"/>
      </group> <!-- Regression -->
    </groups>
    <test name="Default test" duration-ms="119291" started-at="2015-05-07T09:55:53Z" finished-at="2015-05-07T09:57:52Z">
      <class name="com.projectname.test.functional.login.LoginTest">
        <test-method status="PASS" signature="genericSetUp()[pri:0, instance:com.projectname.test.functional.login.LoginTest@1ce487b]" name="genericSetUp" is-config="true" duration-ms="16911" started-at="2015-05-07T15:25:53Z" finished-at="2015-05-07T15:26:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- genericSetUp -->
        <test-method status="FAIL" signature="loginTest()[pri:0, instance:com.projectname.test.functional.login.LoginTest@1ce487b]" name="loginTest" duration-ms="26151" started-at="2015-05-07T15:26:10Z" finished-at="2015-05-07T15:26:36Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Timed out after 20 seconds waiting for com.projectname.testutils.seleniumutils.SeleniumWebDriver$1@1bb4fce
Build info: version: '2.33.0', revision: '4ecaf82108b2a6cc6f006aae81961236eba93358', time: '2013-05-22 12:00:17'
System info: os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.7.0_13'
Driver info: driver.version: SeleniumWebDriver]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Timed out after 20 seconds waiting for com.projectname.testutils.seleniumutils.SeleniumWebDriver$1@1bb4fce
Build info: version: '2.33.0', revision: '4ecaf82108b2a6cc6f006aae81961236eba93358', time: '2013-05-22 12:00:17'
System info: os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.7.0_13'
Driver info: driver.version: SeleniumWebDriver
	at org.junit.Assert.fail(Assert.java:93)
	at com.projectname.testutils.genericutility.ExceptionHandler.takeScreenshot(ExceptionHandler.java:74)
	at com.projectname.testutils.genericutility.ExceptionHandler.<init>(ExceptionHandler.java:41)
	at com.projectname.testutils.seleniumutils.SeleniumWebDriver.waitForElement(SeleniumWebDriver.java:152)
	at com.projectname.testutils.pages.IntranetHomePage.<init>(IntranetHomePage.java:22)
	at com.projectname.testutils.pages.LoginPage.login(LoginPage.java:42)
	at com.projectname.test.functional.login.LoginTest.loginTest(LoginTest.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.projectname.test.functional.login.LoginTest@1ce487b]" name="tearDown" is-config="true" duration-ms="1462" started-at="2015-05-07T15:26:36Z" finished-at="2015-05-07T15:26:38Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=loginTest status=FAILURE method=LoginTest.loginTest()[pri:0, instance:com.projectname.test.functional.login.LoginTest@1ce487b] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="genericSetUp()[pri:0, instance:com.projectname.test.functional.login.LoginTest@1ce487b]" name="genericSetUp" is-config="true" duration-ms="9871" started-at="2015-05-07T15:26:38Z" finished-at="2015-05-07T15:26:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- genericSetUp -->
        <test-method status="FAIL" signature="loginTest()[pri:0, instance:com.projectname.test.functional.login.LoginTest@1ce487b]" name="loginTest" duration-ms="26074" started-at="2015-05-07T15:26:48Z" finished-at="2015-05-07T15:27:14Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Timed out after 20 seconds waiting for com.projectname.testutils.seleniumutils.SeleniumWebDriver$1@1c61093
Build info: version: '2.33.0', revision: '4ecaf82108b2a6cc6f006aae81961236eba93358', time: '2013-05-22 12:00:17'
System info: os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.7.0_13'
Driver info: driver.version: SeleniumWebDriver]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Timed out after 20 seconds waiting for com.projectname.testutils.seleniumutils.SeleniumWebDriver$1@1c61093
Build info: version: '2.33.0', revision: '4ecaf82108b2a6cc6f006aae81961236eba93358', time: '2013-05-22 12:00:17'
System info: os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.7.0_13'
Driver info: driver.version: SeleniumWebDriver
	at org.junit.Assert.fail(Assert.java:93)
	at com.projectname.testutils.genericutility.ExceptionHandler.takeScreenshot(ExceptionHandler.java:74)
	at com.projectname.testutils.genericutility.ExceptionHandler.<init>(ExceptionHandler.java:41)
	at com.projectname.testutils.seleniumutils.SeleniumWebDriver.waitForElement(SeleniumWebDriver.java:152)
	at com.projectname.testutils.pages.IntranetHomePage.<init>(IntranetHomePage.java:22)
	at com.projectname.testutils.pages.LoginPage.login(LoginPage.java:42)
	at com.projectname.test.functional.login.LoginTest.loginTest(LoginTest.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1049)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1254)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.projectname.test.functional.login.LoginTest@1ce487b]" name="tearDown" is-config="true" duration-ms="1308" started-at="2015-05-07T15:27:14Z" finished-at="2015-05-07T15:27:15Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=loginTest status=FAILURE method=LoginTest.loginTest()[pri:0, instance:com.projectname.test.functional.login.LoginTest@1ce487b] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="genericSetUp()[pri:0, instance:com.projectname.test.functional.login.LoginTest@1ce487b]" name="genericSetUp" is-config="true" duration-ms="9566" started-at="2015-05-07T15:27:15Z" finished-at="2015-05-07T15:27:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- genericSetUp -->
        <test-method status="FAIL" signature="loginTest()[pri:0, instance:com.projectname.test.functional.login.LoginTest@1ce487b]" name="loginTest" duration-ms="26371" started-at="2015-05-07T15:27:24Z" finished-at="2015-05-07T15:27:51Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Timed out after 20 seconds waiting for com.projectname.testutils.seleniumutils.SeleniumWebDriver$1@139132f
Build info: version: '2.33.0', revision: '4ecaf82108b2a6cc6f006aae81961236eba93358', time: '2013-05-22 12:00:17'
System info: os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.7.0_13'
Driver info: driver.version: SeleniumWebDriver]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Timed out after 20 seconds waiting for com.projectname.testutils.seleniumutils.SeleniumWebDriver$1@139132f
Build info: version: '2.33.0', revision: '4ecaf82108b2a6cc6f006aae81961236eba93358', time: '2013-05-22 12:00:17'
System info: os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.7.0_13'
Driver info: driver.version: SeleniumWebDriver
	at org.junit.Assert.fail(Assert.java:93)
	at com.projectname.testutils.genericutility.ExceptionHandler.takeScreenshot(ExceptionHandler.java:74)
	at com.projectname.testutils.genericutility.ExceptionHandler.<init>(ExceptionHandler.java:41)
	at com.projectname.testutils.seleniumutils.SeleniumWebDriver.waitForElement(SeleniumWebDriver.java:152)
	at com.projectname.testutils.pages.IntranetHomePage.<init>(IntranetHomePage.java:22)
	at com.projectname.testutils.pages.LoginPage.login(LoginPage.java:42)
	at com.projectname.test.functional.login.LoginTest.loginTest(LoginTest.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1049)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1254)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.projectname.test.functional.login.LoginTest@1ce487b]" name="tearDown" is-config="true" duration-ms="1558" started-at="2015-05-07T15:27:51Z" finished-at="2015-05-07T15:27:52Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=loginTest status=FAILURE method=LoginTest.loginTest()[pri:0, instance:com.projectname.test.functional.login.LoginTest@1ce487b] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.projectname.test.functional.login.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
